# Application configuration.
server.port=8092
 
# Local mongodb configuration.
#spring.data.mongodb.uri=mongodb://root:root@localhost:27017/micros_servicos
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=micros_servicos

# Atlas mongodb configuration.
#spring.data.mongodb.uri=mongodb+srv://neuber:Alice%401511@cluster0-vzye9.gcp.mongodb.net/test?retryWrites=true&w=majority
 
# Logging configuration.
logging.level.com.assignment.springboot.mongo=DEBUG
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n

